export const hospitalDepartments = [
  'General Medicine',
  'Emergency',
  'Cardiology',
  'Pediatrics',
  'Obstetrics and Gynecology',
  'Gynecology',
  'Orthopedics',
  'Surgery',
  'Neurology',
  'Radiology',
  'Laboratory',
  'Pharmacy',
  'Dental',
  'Ophthalmology',
  'ENT',
  'Dermatology',
  'Psychiatry',
  'Physiotherapy',
  'Hematology',
  'Oncology',
  'Urology',
  'Nephrology',
  'Gastroenterology',
  'Intensive Care Unit',
  'Maternity',
  'Outpatient Department',
];
