import type { PermissionDefinition, RoleDefinition } from './roles-permissions.types';

export const defaultPermissions: PermissionDefinition[] = [
  { code: 'manage_users', description: 'Create, update, and remove system users' },
  { code: 'manage_roles', description: 'Create, update, and assign roles and permissions' },
  { code: 'manage_departments', description: 'Manage hospital departments' },
  { code: 'create_patient', description: 'Register new patients' },
  { code: 'view_patient', description: 'View patient records' },
  { code: 'update_patient', description: 'Update patient demographic records' },
  { code: 'delete_patient', description: 'Delete patient records' },
  { code: 'create_appointment', description: 'Create and book appointments' },
  { code: 'view_appointment', description: 'View appointments' },
  { code: 'create_encounter', description: 'Create clinical encounters' },
  { code: 'view_encounter', description: 'View clinical encounters' },
  { code: 'update_encounter', description: 'Update clinical encounters' },
  { code: 'close_encounter', description: 'Close clinical encounters' },
  { code: 'create_triage', description: 'Record triage and vital signs' },
  { code: 'view_triage', description: 'View triage and vital signs' },
  { code: 'update_triage', description: 'Update triage and vital signs' },
  { code: 'view_emr', description: 'View electronic medical records' },
  { code: 'create_clinical_note', description: 'Create clinical notes' },
  { code: 'update_clinical_note', description: 'Update clinical notes' },
  { code: 'create_diagnosis', description: 'Create diagnoses' },
  { code: 'update_diagnosis', description: 'Update diagnoses' },
  { code: 'view_admission', description: 'View inpatient admissions' },
  { code: 'create_admission', description: 'Create inpatient admissions' },
  { code: 'update_admission', description: 'Update inpatient admissions' },
  { code: 'discharge_admission', description: 'Discharge inpatient admissions' },
  { code: 'manage_wards', description: 'Manage wards and rooms' },
  { code: 'view_beds', description: 'View ward rooms and beds' },
  { code: 'manage_beds', description: 'Manage beds' },
  { code: 'assign_bed', description: 'Assign inpatient beds' },
  { code: 'view_bed_assignments', description: 'View inpatient bed assignments' },
  { code: 'view_invoice', description: 'View invoices and payments' },
  { code: 'create_invoice', description: 'Create invoices' },
  { code: 'update_invoice', description: 'Update invoices and invoice items' },
  { code: 'receive_payment', description: 'Receive payments' },
  { code: 'view_reports', description: 'View reports' },
  { code: 'view_audit_logs', description: 'View audit logs' },
];

const allPermissions = defaultPermissions.map((permission) => permission.code);

export const defaultRoles: RoleDefinition[] = [
  {
    name: 'Super Admin',
    description: 'Full system access',
    permissions: allPermissions,
  },
  {
    name: 'Hospital Admin',
    description: 'Hospital administration and operations access',
    permissions: [
      'manage_users',
      'manage_departments',
      'create_patient',
      'view_patient',
      'update_patient',
      'delete_patient',
      'create_appointment',
      'view_appointment',
      'create_encounter',
      'view_encounter',
      'update_encounter',
      'close_encounter',
      'create_triage',
      'view_triage',
      'update_triage',
      'view_emr',
      'create_clinical_note',
      'update_clinical_note',
      'create_diagnosis',
      'update_diagnosis',
      'view_admission',
      'create_admission',
      'update_admission',
      'discharge_admission',
      'manage_wards',
      'view_beds',
      'manage_beds',
      'assign_bed',
      'view_bed_assignments',
      'view_invoice',
      'create_invoice',
      'update_invoice',
      'receive_payment',
      'view_reports',
      'view_audit_logs',
    ],
  },
  {
    name: 'Receptionist',
    description: 'Front desk patient registration and scheduling access',
    permissions: [
      'create_patient',
      'view_patient',
      'update_patient',
      'create_appointment',
      'view_appointment',
      'create_encounter',
      'view_encounter',
      'update_encounter',
    ],
  },
  {
    name: 'Doctor',
    description: 'Clinical consultation and EMR access',
    permissions: [
      'view_patient',
      'view_appointment',
      'view_encounter',
      'update_encounter',
      'close_encounter',
      'view_triage',
      'view_emr',
      'create_clinical_note',
      'update_clinical_note',
      'create_diagnosis',
      'update_diagnosis',
      'view_admission',
      'create_admission',
      'update_admission',
      'discharge_admission',
      'view_beds',
      'assign_bed',
      'view_bed_assignments',
    ],
  },
  {
    name: 'Nurse',
    description: 'Triage and nursing workflow access',
    permissions: ['view_patient', 'view_encounter', 'create_triage', 'view_triage', 'update_triage', 'view_emr', 'view_admission', 'view_beds', 'assign_bed', 'view_bed_assignments'],
  },
  {
    name: 'Cashier',
    description: 'Billing and payment collection access',
    permissions: ['view_patient', 'view_invoice', 'create_invoice', 'update_invoice', 'receive_payment'],
  },
  {
    name: 'Patient',
    description: 'Patient self-service access',
    permissions: ['view_patient', 'update_patient', 'view_appointment', 'create_appointment'],
  },
];

export const defaultRoleByUserType: Record<string, string> = {
  Admin: 'Hospital Admin',
  Staff: 'Receptionist',
  Patient: 'Patient',
};
